name: pentest
favicon: null
layout_spectrum: 0.5139
typography_spectrum: 0.1733867679427349
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2e3942'
    - '#706c69'
    - '#fefefb'
    - '#9ea0a9'
  brandStrength: 0.25
  lightness: 0.7348960750960805
  saturation: 0.5695086451526948
  rhythmicContrast: 0.18584936979381161
purpose:
  - name: null
    item: null
    url: null
